//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualDoctor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConcreteSymptomDiseaseConnection
    {
        public int Id { get; set; }
        public int Disease { get; set; }
        public int Symptom { get; set; }
        public Nullable<double> ProbabilisticEvaluation { get; set; }
        public Nullable<int> OccurencesNumber { get; set; }
        public Nullable<int> YesAnswers { get; set; }
        public Nullable<int> ProbablyYesAnswers { get; set; }
        public Nullable<int> DontKnowAnswers { get; set; }
        public Nullable<int> ProbablyNotAnswers { get; set; }
        public Nullable<int> NotAnswers { get; set; }
    
        public virtual Disease Disease1 { get; set; }
        public virtual Symptom Symptom1 { get; set; }
    }
}
