//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualDoctor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disease
    {
        public Disease()
        {
            this.ConcreteSymptomDiseaseConnections = new HashSet<ConcreteSymptomDiseaseConnection>();
            this.DiseaseCorelations = new HashSet<DiseaseCorelation>();
            this.DiseaseCorelations1 = new HashSet<DiseaseCorelation>();
            this.PatientDiseaseCases = new HashSet<PatientDiseaseCas>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> OccurencesNumber { get; set; }
    
        public virtual ICollection<ConcreteSymptomDiseaseConnection> ConcreteSymptomDiseaseConnections { get; set; }
        public virtual ICollection<DiseaseCorelation> DiseaseCorelations { get; set; }
        public virtual ICollection<DiseaseCorelation> DiseaseCorelations1 { get; set; }
        public virtual ICollection<PatientDiseaseCas> PatientDiseaseCases { get; set; }
    }
}
