//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualDoctor
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiseaseCorelation
    {
        public int Id { get; set; }
        public int DiseaseA { get; set; }
        public int DiseaseB { get; set; }
        public Nullable<int> CommonCases { get; set; }
        public Nullable<int> CorelationPower { get; set; }
        public Nullable<int> CorelationDirection { get; set; }
    
        public virtual Disease Disease { get; set; }
        public virtual Disease Disease1 { get; set; }
    }
}
