//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualDoctor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.PatientDiseaseCases = new HashSet<PatientDiseaseCas>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MailAddress { get; set; }
        public string Password { get; set; }
        public Nullable<int> Activated { get; set; }
        public string PeselNumber { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual ICollection<PatientDiseaseCas> PatientDiseaseCases { get; set; }
    }
}
