//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualDoctor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDiseaseCas
    {
        public int Id { get; set; }
        public int Patient { get; set; }
        public int Disease { get; set; }
        public Nullable<System.DateTime> DiagnosisDate { get; set; }
        public Nullable<System.DateTime> CureDate { get; set; }
        public Nullable<int> WasDeadly { get; set; }
        public string CaseDescription { get; set; }
    
        public virtual Disease Disease1 { get; set; }
        public virtual Patient Patient1 { get; set; }
    }
}
