//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualDoctor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SymptomCathegory
    {
        public SymptomCathegory()
        {
            this.SymptomCathegories1 = new HashSet<SymptomCathegory>();
            this.Symptoms = new HashSet<Symptom>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentCathegory { get; set; }
    
        public virtual ICollection<SymptomCathegory> SymptomCathegories1 { get; set; }
        public virtual SymptomCathegory SymptomCathegory1 { get; set; }
        public virtual ICollection<Symptom> Symptoms { get; set; }
    }
}
